/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart {
  'id' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'totalPriceCents' : bigint,
  'items' : Array<CartItem>,
  'products' : Array<Product>,
}
export interface CartItem {
  'color' : ProductColor,
  'size' : ProductSize,
  'productId' : string,
  'quantity' : bigint,
}
export interface ContactForm {
  'id' : string,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'replied' : boolean,
}
export interface DeliveryLocation {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'customer' : Principal,
  'createdAt' : bigint,
  'totalPriceCents' : bigint,
  'locations' : Array<DeliveryLocation>,
  'items' : Array<CartItem>,
  'paymentIntentId' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'paid' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : string,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'sizes' : Array<ProductSize>,
  'category' : ProductCategory,
  'colors' : Array<ProductColor>,
  'priceCents' : bigint,
  'images' : Array<ProductImage>,
}
export type ProductCategory = { 'art' : null } |
  { 'clothing' : null } |
  { 'accessories' : null } |
  { 'other' : string } |
  { 'footwear' : null } |
  { 'jewelry' : null } |
  { 'fragrances' : null } |
  { 'electronics' : null } |
  { 'homeDecor' : null };
export type ProductColor = { 'red' : null } |
  { 'custom' : string } |
  { 'blue' : null } |
  { 'gold' : null } |
  { 'green' : null } |
  { 'black' : null } |
  { 'silver' : null } |
  { 'white' : null };
export type ProductImage = Uint8Array;
export type ProductSize = { 'l' : null } |
  { 'm' : null } |
  { 's' : null } |
  { 'xl' : null } |
  { 'xs' : null } |
  { 'xxl' : null } |
  { 'custom' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[string], undefined>,
  'createCart' : ActorMethod<[Cart], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[Order], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[string], [] | [Cart]>,
  'getContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrderLocations' : ActorMethod<[string], Array<DeliveryLocation>>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markContactFormReplied' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<[ContactForm], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCart' : ActorMethod<[Cart], undefined>,
  'updateOrder' : ActorMethod<[Order], undefined>,
  'updateOrderLocation' : ActorMethod<[string, DeliveryLocation], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];