/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductSize = IDL.Variant({
  'l' : IDL.Null,
  'm' : IDL.Null,
  's' : IDL.Null,
  'xl' : IDL.Null,
  'xs' : IDL.Null,
  'xxl' : IDL.Null,
  'custom' : IDL.Text,
});
export const ProductCategory = IDL.Variant({
  'art' : IDL.Null,
  'clothing' : IDL.Null,
  'accessories' : IDL.Null,
  'other' : IDL.Text,
  'footwear' : IDL.Null,
  'jewelry' : IDL.Null,
  'fragrances' : IDL.Null,
  'electronics' : IDL.Null,
  'homeDecor' : IDL.Null,
});
export const ProductColor = IDL.Variant({
  'red' : IDL.Null,
  'custom' : IDL.Text,
  'blue' : IDL.Null,
  'gold' : IDL.Null,
  'green' : IDL.Null,
  'black' : IDL.Null,
  'silver' : IDL.Null,
  'white' : IDL.Null,
});
export const ProductImage = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(ProductSize),
  'category' : ProductCategory,
  'colors' : IDL.Vec(ProductColor),
  'priceCents' : IDL.Nat,
  'images' : IDL.Vec(ProductImage),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CartItem = IDL.Record({
  'color' : ProductColor,
  'size' : ProductSize,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalPriceCents' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
  'products' : IDL.Vec(Product),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const DeliveryLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalPriceCents' : IDL.Nat,
  'locations' : IDL.Vec(DeliveryLocation),
  'items' : IDL.Vec(CartItem),
  'paymentIntentId' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'replied' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'createCart' : IDL.Func([Cart], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([Order], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([IDL.Text], [IDL.Opt(Cart)], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrderLocations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DeliveryLocation)],
      ['query'],
    ),
  'getOrdersByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactFormReplied' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactForm' : IDL.Func([ContactForm], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCart' : IDL.Func([Cart], [], []),
  'updateOrder' : IDL.Func([Order], [], []),
  'updateOrderLocation' : IDL.Func([IDL.Text, DeliveryLocation], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductSize = IDL.Variant({
    'l' : IDL.Null,
    'm' : IDL.Null,
    's' : IDL.Null,
    'xl' : IDL.Null,
    'xs' : IDL.Null,
    'xxl' : IDL.Null,
    'custom' : IDL.Text,
  });
  const ProductCategory = IDL.Variant({
    'art' : IDL.Null,
    'clothing' : IDL.Null,
    'accessories' : IDL.Null,
    'other' : IDL.Text,
    'footwear' : IDL.Null,
    'jewelry' : IDL.Null,
    'fragrances' : IDL.Null,
    'electronics' : IDL.Null,
    'homeDecor' : IDL.Null,
  });
  const ProductColor = IDL.Variant({
    'red' : IDL.Null,
    'custom' : IDL.Text,
    'blue' : IDL.Null,
    'gold' : IDL.Null,
    'green' : IDL.Null,
    'black' : IDL.Null,
    'silver' : IDL.Null,
    'white' : IDL.Null,
  });
  const ProductImage = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(ProductSize),
    'category' : ProductCategory,
    'colors' : IDL.Vec(ProductColor),
    'priceCents' : IDL.Nat,
    'images' : IDL.Vec(ProductImage),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'color' : ProductColor,
    'size' : ProductSize,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalPriceCents' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
    'products' : IDL.Vec(Product),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const DeliveryLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalPriceCents' : IDL.Nat,
    'locations' : IDL.Vec(DeliveryLocation),
    'items' : IDL.Vec(CartItem),
    'paymentIntentId' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'replied' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'createCart' : IDL.Func([Cart], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([Order], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([IDL.Text], [IDL.Opt(Cart)], ['query']),
    'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrderLocations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DeliveryLocation)],
        ['query'],
      ),
    'getOrdersByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactFormReplied' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactForm' : IDL.Func([ContactForm], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCart' : IDL.Func([Cart], [], []),
    'updateOrder' : IDL.Func([Order], [], []),
    'updateOrderLocation' : IDL.Func([IDL.Text, DeliveryLocation], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };