/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ProductColor = {
    __kind__: "red";
    red: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blue";
    blue: null;
} | {
    __kind__: "gold";
    gold: null;
} | {
    __kind__: "green";
    green: null;
} | {
    __kind__: "black";
    black: null;
} | {
    __kind__: "silver";
    silver: null;
} | {
    __kind__: "white";
    white: null;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ContactForm {
    id: string;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    replied: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ProductImage = Uint8Array;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: string;
    status: OrderStatus;
    customer: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    locations: Array<DeliveryLocation>;
    items: Array<CartItem>;
    paymentIntentId: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type ProductSize = {
    __kind__: "l";
    l: null;
} | {
    __kind__: "m";
    m: null;
} | {
    __kind__: "s";
    s: null;
} | {
    __kind__: "xl";
    xl: null;
} | {
    __kind__: "xs";
    xs: null;
} | {
    __kind__: "xxl";
    xxl: null;
} | {
    __kind__: "custom";
    custom: string;
};
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface DeliveryLocation {
    latitude: number;
    longitude: number;
    timestamp: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Cart {
    id: string;
    owner: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    items: Array<CartItem>;
    products: Array<Product>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface CartItem {
    color: ProductColor;
    size: ProductSize;
    productId: string;
    quantity: bigint;
}
export type ProductCategory = {
    __kind__: "art";
    art: null;
} | {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "accessories";
    accessories: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "footwear";
    footwear: null;
} | {
    __kind__: "jewelry";
    jewelry: null;
} | {
    __kind__: "fragrances";
    fragrances: null;
} | {
    __kind__: "electronics";
    electronics: null;
} | {
    __kind__: "homeDecor";
    homeDecor: null;
};
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Product {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<ProductSize>;
    category: ProductCategory;
    colors: Array<ProductColor>;
    priceCents: bigint;
    images: Array<ProductImage>;
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    paid = "paid",
    delivered = "delivered",
    processing = "processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(product: Product): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(cartId: string): Promise<void>;
    createCart(cart: Cart): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrder(order: Order): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(cartId: string): Promise<Cart | null>;
    getContactForms(): Promise<Array<ContactForm>>;
    getFeaturedProducts(): Promise<Array<Product>>;
    getOrder(id: string): Promise<Order | null>;
    getOrderLocations(orderId: string): Promise<Array<DeliveryLocation>>;
    getOrdersByCustomer(customer: Principal): Promise<Array<Order>>;
    getProduct(id: string): Promise<Product>;
    getProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markContactFormReplied(formId: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitContactForm(form: ContactForm): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCart(cart: Cart): Promise<void>;
    updateOrder(order: Order): Promise<void>;
    updateOrderLocation(orderId: string, location: DeliveryLocation): Promise<void>;
    updateOrderStatus(orderId: string, status: OrderStatus): Promise<void>;
    updateProduct(product: Product): Promise<void>;
}
import type { Cart as _Cart, CartItem as _CartItem, DeliveryLocation as _DeliveryLocation, Order as _Order, OrderStatus as _OrderStatus, Product as _Product, ProductCategory as _ProductCategory, ProductColor as _ProductColor, ProductImage as _ProductImage, ProductSize as _ProductSize, StripeSessionStatus as _StripeSessionStatus, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async clearCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart(arg0);
            return result;
        }
    }
    async createCart(arg0: Cart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCart(to_candid_Cart_n20(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCart(to_candid_Cart_n20(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_Order_n26(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_Order_n26(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCart(arg0: string): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart(arg0);
                return from_candid_opt_n51(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart(arg0);
            return from_candid_opt_n51(this.uploadFile, this.downloadFile, result);
        }
    }
    async getContactForms(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactForms();
            return result;
        }
    }
    async getFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts();
                return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts();
            return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n54(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n54(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrderLocations(arg0: string): Promise<Array<DeliveryLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderLocations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderLocations(arg0);
            return result;
        }
    }
    async getOrdersByCustomer(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomer(arg0);
                return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomer(arg0);
            return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n13(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n13(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n55(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n55(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markContactFormReplied(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactFormReplied(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactFormReplied(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: ContactForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCart(arg0: Cart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCart(to_candid_Cart_n20(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCart(to_candid_Cart_n20(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(to_candid_Order_n26(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(to_candid_Order_n26(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateOrderLocation(arg0: string, arg1: DeliveryLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderLocation(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n28(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n28(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_Product_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_Product_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CartItem_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n37(uploadFile, downloadFile, value);
}
function from_candid_Cart_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Cart {
    return from_candid_record_n53(uploadFile, downloadFile, value);
}
function from_candid_OrderStatus_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n34(uploadFile, downloadFile, value);
}
function from_candid_Order_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n32(uploadFile, downloadFile, value);
}
function from_candid_ProductCategory_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n47(uploadFile, downloadFile, value);
}
function from_candid_ProductColor_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductColor): ProductColor {
    return from_candid_variant_n39(uploadFile, downloadFile, value);
}
function from_candid_ProductSize_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductSize): ProductSize {
    return from_candid_variant_n41(uploadFile, downloadFile, value);
}
function from_candid_Product_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n44(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n56(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cart]): Cart | null {
    return value.length === 0 ? null : from_candid_Cart_n52(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n31(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    customer: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    locations: Array<_DeliveryLocation>;
    items: Array<_CartItem>;
    paymentIntentId: string;
}): {
    id: string;
    status: OrderStatus;
    customer: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    locations: Array<DeliveryLocation>;
    items: Array<CartItem>;
    paymentIntentId: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n33(uploadFile, downloadFile, value.status),
        customer: value.customer,
        createdAt: value.createdAt,
        totalPriceCents: value.totalPriceCents,
        locations: value.locations,
        items: from_candid_vec_n35(uploadFile, downloadFile, value.items),
        paymentIntentId: value.paymentIntentId
    };
}
function from_candid_record_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: _ProductColor;
    size: _ProductSize;
    productId: string;
    quantity: bigint;
}): {
    color: ProductColor;
    size: ProductSize;
    productId: string;
    quantity: bigint;
} {
    return {
        color: from_candid_ProductColor_n38(uploadFile, downloadFile, value.color),
        size: from_candid_ProductSize_n40(uploadFile, downloadFile, value.size),
        productId: value.productId,
        quantity: value.quantity
    };
}
function from_candid_record_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<_ProductSize>;
    category: _ProductCategory;
    colors: Array<_ProductColor>;
    priceCents: bigint;
    images: Array<_ProductImage>;
}): {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<ProductSize>;
    category: ProductCategory;
    colors: Array<ProductColor>;
    priceCents: bigint;
    images: Array<ProductImage>;
} {
    return {
        id: value.id,
        featured: value.featured,
        inStock: value.inStock,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        sizes: from_candid_vec_n45(uploadFile, downloadFile, value.sizes),
        category: from_candid_ProductCategory_n46(uploadFile, downloadFile, value.category),
        colors: from_candid_vec_n48(uploadFile, downloadFile, value.colors),
        priceCents: value.priceCents,
        images: value.images
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    items: Array<_CartItem>;
    products: Array<_Product>;
}): {
    id: string;
    owner: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    items: Array<CartItem>;
    products: Array<Product>;
} {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        totalPriceCents: value.totalPriceCents,
        items: from_candid_vec_n35(uploadFile, downloadFile, value.items),
        products: from_candid_vec_n42(uploadFile, downloadFile, value.products)
    };
}
function from_candid_record_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n58(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    paid: null;
} | {
    delivered: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "paid" in value ? OrderStatus.paid : "delivered" in value ? OrderStatus.delivered : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    custom: string;
} | {
    blue: null;
} | {
    gold: null;
} | {
    green: null;
} | {
    black: null;
} | {
    silver: null;
} | {
    white: null;
}): {
    __kind__: "red";
    red: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blue";
    blue: null;
} | {
    __kind__: "gold";
    gold: null;
} | {
    __kind__: "green";
    green: null;
} | {
    __kind__: "black";
    black: null;
} | {
    __kind__: "silver";
    silver: null;
} | {
    __kind__: "white";
    white: null;
} {
    return "red" in value ? {
        __kind__: "red",
        red: value.red
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "blue" in value ? {
        __kind__: "blue",
        blue: value.blue
    } : "gold" in value ? {
        __kind__: "gold",
        gold: value.gold
    } : "green" in value ? {
        __kind__: "green",
        green: value.green
    } : "black" in value ? {
        __kind__: "black",
        black: value.black
    } : "silver" in value ? {
        __kind__: "silver",
        silver: value.silver
    } : "white" in value ? {
        __kind__: "white",
        white: value.white
    } : value;
}
function from_candid_variant_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    l: null;
} | {
    m: null;
} | {
    s: null;
} | {
    xl: null;
} | {
    xs: null;
} | {
    xxl: null;
} | {
    custom: string;
}): {
    __kind__: "l";
    l: null;
} | {
    __kind__: "m";
    m: null;
} | {
    __kind__: "s";
    s: null;
} | {
    __kind__: "xl";
    xl: null;
} | {
    __kind__: "xs";
    xs: null;
} | {
    __kind__: "xxl";
    xxl: null;
} | {
    __kind__: "custom";
    custom: string;
} {
    return "l" in value ? {
        __kind__: "l",
        l: value.l
    } : "m" in value ? {
        __kind__: "m",
        m: value.m
    } : "s" in value ? {
        __kind__: "s",
        s: value.s
    } : "xl" in value ? {
        __kind__: "xl",
        xl: value.xl
    } : "xs" in value ? {
        __kind__: "xs",
        xs: value.xs
    } : "xxl" in value ? {
        __kind__: "xxl",
        xxl: value.xxl
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : value;
}
function from_candid_variant_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    art: null;
} | {
    clothing: null;
} | {
    accessories: null;
} | {
    other: string;
} | {
    footwear: null;
} | {
    jewelry: null;
} | {
    fragrances: null;
} | {
    electronics: null;
} | {
    homeDecor: null;
}): {
    __kind__: "art";
    art: null;
} | {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "accessories";
    accessories: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "footwear";
    footwear: null;
} | {
    __kind__: "jewelry";
    jewelry: null;
} | {
    __kind__: "fragrances";
    fragrances: null;
} | {
    __kind__: "electronics";
    electronics: null;
} | {
    __kind__: "homeDecor";
    homeDecor: null;
} {
    return "art" in value ? {
        __kind__: "art",
        art: value.art
    } : "clothing" in value ? {
        __kind__: "clothing",
        clothing: value.clothing
    } : "accessories" in value ? {
        __kind__: "accessories",
        accessories: value.accessories
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "footwear" in value ? {
        __kind__: "footwear",
        footwear: value.footwear
    } : "jewelry" in value ? {
        __kind__: "jewelry",
        jewelry: value.jewelry
    } : "fragrances" in value ? {
        __kind__: "fragrances",
        fragrances: value.fragrances
    } : "electronics" in value ? {
        __kind__: "electronics",
        electronics: value.electronics
    } : "homeDecor" in value ? {
        __kind__: "homeDecor",
        homeDecor: value.homeDecor
    } : value;
}
function from_candid_variant_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n57(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n31(uploadFile, downloadFile, x));
}
function from_candid_vec_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n36(uploadFile, downloadFile, x));
}
function from_candid_vec_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n43(uploadFile, downloadFile, x));
}
function from_candid_vec_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductSize>): Array<ProductSize> {
    return value.map((x)=>from_candid_ProductSize_n40(uploadFile, downloadFile, x));
}
function from_candid_vec_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductColor>): Array<ProductColor> {
    return value.map((x)=>from_candid_ProductColor_n38(uploadFile, downloadFile, x));
}
function to_candid_CartItem_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n24(uploadFile, downloadFile, value);
}
function to_candid_Cart_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cart): _Cart {
    return to_candid_record_n21(uploadFile, downloadFile, value);
}
function to_candid_OrderStatus_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n29(uploadFile, downloadFile, value);
}
function to_candid_Order_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n27(uploadFile, downloadFile, value);
}
function to_candid_ProductCategory_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n14(uploadFile, downloadFile, value);
}
function to_candid_ProductColor_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductColor): _ProductColor {
    return to_candid_variant_n17(uploadFile, downloadFile, value);
}
function to_candid_ProductSize_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductSize): _ProductSize {
    return to_candid_variant_n12(uploadFile, downloadFile, value);
}
function to_candid_Product_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n9(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    items: Array<CartItem>;
    products: Array<Product>;
}): {
    id: string;
    owner: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    items: Array<_CartItem>;
    products: Array<_Product>;
} {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        totalPriceCents: value.totalPriceCents,
        items: to_candid_vec_n22(uploadFile, downloadFile, value.items),
        products: to_candid_vec_n25(uploadFile, downloadFile, value.products)
    };
}
function to_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: ProductColor;
    size: ProductSize;
    productId: string;
    quantity: bigint;
}): {
    color: _ProductColor;
    size: _ProductSize;
    productId: string;
    quantity: bigint;
} {
    return {
        color: to_candid_ProductColor_n16(uploadFile, downloadFile, value.color),
        size: to_candid_ProductSize_n11(uploadFile, downloadFile, value.size),
        productId: value.productId,
        quantity: value.quantity
    };
}
function to_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: OrderStatus;
    customer: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    locations: Array<DeliveryLocation>;
    items: Array<CartItem>;
    paymentIntentId: string;
}): {
    id: string;
    status: _OrderStatus;
    customer: Principal;
    createdAt: bigint;
    totalPriceCents: bigint;
    locations: Array<_DeliveryLocation>;
    items: Array<_CartItem>;
    paymentIntentId: string;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n28(uploadFile, downloadFile, value.status),
        customer: value.customer,
        createdAt: value.createdAt,
        totalPriceCents: value.totalPriceCents,
        locations: value.locations,
        items: to_candid_vec_n22(uploadFile, downloadFile, value.items),
        paymentIntentId: value.paymentIntentId
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<ProductSize>;
    category: ProductCategory;
    colors: Array<ProductColor>;
    priceCents: bigint;
    images: Array<ProductImage>;
}): {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<_ProductSize>;
    category: _ProductCategory;
    colors: Array<_ProductColor>;
    priceCents: bigint;
    images: Array<_ProductImage>;
} {
    return {
        id: value.id,
        featured: value.featured,
        inStock: value.inStock,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        sizes: to_candid_vec_n10(uploadFile, downloadFile, value.sizes),
        category: to_candid_ProductCategory_n13(uploadFile, downloadFile, value.category),
        colors: to_candid_vec_n15(uploadFile, downloadFile, value.colors),
        priceCents: value.priceCents,
        images: value.images
    };
}
function to_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "l";
    l: null;
} | {
    __kind__: "m";
    m: null;
} | {
    __kind__: "s";
    s: null;
} | {
    __kind__: "xl";
    xl: null;
} | {
    __kind__: "xs";
    xs: null;
} | {
    __kind__: "xxl";
    xxl: null;
} | {
    __kind__: "custom";
    custom: string;
}): {
    l: null;
} | {
    m: null;
} | {
    s: null;
} | {
    xl: null;
} | {
    xs: null;
} | {
    xxl: null;
} | {
    custom: string;
} {
    return value.__kind__ === "l" ? {
        l: value.l
    } : value.__kind__ === "m" ? {
        m: value.m
    } : value.__kind__ === "s" ? {
        s: value.s
    } : value.__kind__ === "xl" ? {
        xl: value.xl
    } : value.__kind__ === "xs" ? {
        xs: value.xs
    } : value.__kind__ === "xxl" ? {
        xxl: value.xxl
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value;
}
function to_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "art";
    art: null;
} | {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "accessories";
    accessories: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "footwear";
    footwear: null;
} | {
    __kind__: "jewelry";
    jewelry: null;
} | {
    __kind__: "fragrances";
    fragrances: null;
} | {
    __kind__: "electronics";
    electronics: null;
} | {
    __kind__: "homeDecor";
    homeDecor: null;
}): {
    art: null;
} | {
    clothing: null;
} | {
    accessories: null;
} | {
    other: string;
} | {
    footwear: null;
} | {
    jewelry: null;
} | {
    fragrances: null;
} | {
    electronics: null;
} | {
    homeDecor: null;
} {
    return value.__kind__ === "art" ? {
        art: value.art
    } : value.__kind__ === "clothing" ? {
        clothing: value.clothing
    } : value.__kind__ === "accessories" ? {
        accessories: value.accessories
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "footwear" ? {
        footwear: value.footwear
    } : value.__kind__ === "jewelry" ? {
        jewelry: value.jewelry
    } : value.__kind__ === "fragrances" ? {
        fragrances: value.fragrances
    } : value.__kind__ === "electronics" ? {
        electronics: value.electronics
    } : value.__kind__ === "homeDecor" ? {
        homeDecor: value.homeDecor
    } : value;
}
function to_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "red";
    red: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blue";
    blue: null;
} | {
    __kind__: "gold";
    gold: null;
} | {
    __kind__: "green";
    green: null;
} | {
    __kind__: "black";
    black: null;
} | {
    __kind__: "silver";
    silver: null;
} | {
    __kind__: "white";
    white: null;
}): {
    red: null;
} | {
    custom: string;
} | {
    blue: null;
} | {
    gold: null;
} | {
    green: null;
} | {
    black: null;
} | {
    silver: null;
} | {
    white: null;
} {
    return value.__kind__ === "red" ? {
        red: value.red
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "blue" ? {
        blue: value.blue
    } : value.__kind__ === "gold" ? {
        gold: value.gold
    } : value.__kind__ === "green" ? {
        green: value.green
    } : value.__kind__ === "black" ? {
        black: value.black
    } : value.__kind__ === "silver" ? {
        silver: value.silver
    } : value.__kind__ === "white" ? {
        white: value.white
    } : value;
}
function to_candid_variant_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    paid: null;
} | {
    delivered: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProductSize>): Array<_ProductSize> {
    return value.map((x)=>to_candid_ProductSize_n11(uploadFile, downloadFile, x));
}
function to_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProductColor>): Array<_ProductColor> {
    return value.map((x)=>to_candid_ProductColor_n16(uploadFile, downloadFile, x));
}
function to_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n23(uploadFile, downloadFile, x));
}
function to_candid_vec_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Product>): Array<_Product> {
    return value.map((x)=>to_candid_Product_n8(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
